version: '3.8'

services:
  servidor:
    build: ./servidor
    container_name: servidor
    networks:
      - red_notas

  cliente:
    build: ./cliente
    container_name: cliente
    stdin_open: true
    tty: true
    depends_on:
      servidor: 
        condition: service_started
    networks:
      - red_notas

networks:
  red_notas:
    driver: bridge
